generator:
  class: sfDoctrineGenerator
  param:
    model_class:           Page
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              ~
    plural:                ~
    route_prefix:          page
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        title:             ページの一覧
      filter:  ~
      form:    ~
      edit:
        title:             ページの編集
      new:
        title:             ページの新規作成
