homepage:
  url:      /
  param:    { module: Page, action: Show, slug: top }

page_show:
  url:      /page/:slug
  param:    { module: Page, action: Show }

news_list:
  url:      /news
  param:    { module: Page, action: NewsList }

news_show:
  url:      /news/:slug
  param:    { module: Page, action: NewsShow }

